import { createClient } from 'next-sanity'
import { getExploreStudySetById, listExploreStudySets } from '@/lib/explore-study-sets'
import { sanityApiVersion, sanityExploreDataset, sanityProjectId, sanityReadToken } from '@/lib/sanity/env'
import type { ExploreCard, ExploreGuide, ExploreList, ExploreSection } from './types'

const client = sanityProjectId && sanityExploreDataset ? createClient({ projectId: sanityProjectId, dataset: sanityExploreDataset, apiVersion: sanityApiVersion, useCdn: true, perspective: 'published' }) : null
const projection = `{ "id": _id, "slug": slug.current, title, "subject": subject->title, summary, "coverImage": {"url": coverImage.asset->url, "alt": coverImage.alt}, difficulty, estimatedMinutes, tags, "publishedAt": coalesce(_updatedAt,_createdAt), learningObjectives, sections[]{..., "type": _type}, publicContent, sidebarNotes, seo{..., "ogImage": ogImage.asset->url} }`

async function fetchExplore<T>(query: string, params: Record<string, unknown> = {}, preview = false): Promise<T | null> {
  if (!client) return null
  try { const active = preview && sanityReadToken ? client.withConfig({ useCdn: false, token: sanityReadToken, perspective: 'previewDrafts' }) : client; return await active.fetch<T>(query, params, { next: preview ? { revalidate: 0, tags: ['explore'] } : { revalidate: 300, tags: ['explore'] } }) } catch { return null }
}

const label = (value: string) => ({ mcq: 'Multiple choice', fillBlank: 'Fill in the blanks', writtenTest: 'Written test', tutorLesson: 'Tutor lesson', media: 'Podcast / video' }[value] ?? value.replace(/([A-Z])/g, ' $1').replace(/^./, (c) => c.toUpperCase()))
const normalizeSection = (raw: Record<string, any>): ExploreSection => {
  if (raw.type === 'mcq') return { type: raw.type, label: label(raw.type), items: [{ question: raw.question, options: (raw.options ?? []).map((option: any) => ({ text: option.text, correct: Boolean(option.correct) })), explanation: raw.explanation }] }
  if (raw.type === 'fillBlank') return { type: raw.type, label: label(raw.type), items: [{ prompt: raw.prompt, answer: raw.answer, explanation: raw.explanation }] }
  if (raw.type === 'writtenTest') return { type: raw.type, label: label(raw.type), items: [{ question: raw.question, modelAnswer: raw.modelAnswer, markingPoints: raw.markingPoints ?? [] }] }
  if (raw.type === 'media') return { type: raw.type, label: label(raw.type), url: raw.url, transcript: raw.transcript }
  return { type: raw.type, label: label(raw.type), content: raw.content, items: raw.items, ...(raw.title ? { items: [{ title: raw.title }] } : {}) }
}
const normalizeGuide = (raw: any): ExploreGuide => { const sections = (raw.sections ?? []).map(normalizeSection); return { id: raw.id, slug: raw.slug, title: raw.title, subject: raw.subject ?? 'General', summary: raw.summary ?? '', coverImage: { url: raw.coverImage?.url ?? '/placeholder.jpg', alt: raw.coverImage?.alt ?? raw.title }, itemCounts: Object.fromEntries(sections.map((s: ExploreSection) => [s.type, Math.max(1, s.items?.length ?? (s.content ? 1 : 0))])), difficulty: raw.difficulty ?? 'Beginner', estimatedMinutes: raw.estimatedMinutes ?? 10, tags: raw.tags ?? [], publishedAt: raw.publishedAt, learningObjectives: raw.learningObjectives ?? [], sections, publicContent: raw.publicContent, sidebarNotes: raw.sidebarNotes, seo: { title: raw.seo?.metaTitle, description: raw.seo?.metaDescription, canonicalUrl: raw.seo?.canonicalUrl, ogImage: raw.seo?.ogImage, noIndex: raw.seo?.noIndex } } }

function fallbackGuide(slug: string): ExploreGuide | null { const result = getExploreStudySetById(slug); if (!result) return null; const s: any = result.studySet; const sections: ExploreSection[] = (s.sections ?? []).map((x: any) => ({ type: x.type, label: x.label, content: x.content, items: (x.items ?? []).map((item: any) => ({ prompt: item.prompt, answer: item.answer, question: item.question, options: item.options, correctOptionId: item.correctOptionId, optionIds: item.optionIds, explanation: item.explanation, sentence: item.sentence, idealResponse: item.idealResponse, title: item.title, text: item.text, summary: item.summary, talkingPoints: item.talkingPoints })) })); return { id: s.id, slug: s.slug, title: s.title, subject: s.subject, summary: s.summary, coverImage: { url: s.thumbnail_url, alt: s.title }, itemCounts: Object.fromEntries(sections.map((x) => [x.type, Math.max(1, x.items?.length ?? 0)])), difficulty: s.difficulty, estimatedMinutes: s.estimated_minutes, tags: s.tags, publishedAt: s.created_at, learningObjectives: s.learning_objectives, sections, publicContent: undefined, sidebarNotes: undefined, seo: {} } }
function fallbackList(subject?: string, search?: string, cursor?: string, limit = 12): ExploreList { const old = listExploreStudySets({ subject, search, cursor, limit }); return { data: old.data.map((x) => { const guide = fallbackGuide(x.slug)!; const { learningObjectives: _, sections: __, seo: ___, ...card } = guide; return card }), count: old.count, subjects: old.filters.subjects, nextCursor: old.next_cursor, hasMore: old.pagination.has_more, source: 'fallback' } }

export async function listPublicExplore(params: { subject?: string; search?: string; cursor?: string; limit?: number } = {}): Promise<ExploreList> { const limit = Math.min(24, Math.max(1, params.limit ?? 12)); const all = await fetchExplore<any[]>(`*[_type == "exploreStudySet" && defined(slug.current)] | order(featured desc, sortOrder asc, _updatedAt desc) ${projection}`); if (!all?.length) return fallbackList(params.subject, params.search, params.cursor, limit); const q = (params.search ?? '').trim().toLowerCase(); const filtered = all.map(normalizeGuide).filter((g) => (!params.subject || params.subject === 'All' || g.subject === params.subject) && (!q || [g.title, g.subject, g.summary, ...g.tags].join(' ').toLowerCase().includes(q))); const offset = Math.max(0, Number.parseInt(params.cursor ?? '0', 10) || 0); const data = filtered.slice(offset, offset + limit).map(({ learningObjectives: _, sections: __, seo: ___, publicContent: ____, sidebarNotes: _____, ...card }) => card); const next = offset + data.length < filtered.length ? String(offset + data.length) : null; return { data, count: filtered.length, subjects: ['All', ...new Set(all.map((x) => x.subject ?? 'General'))] as string[], nextCursor: next, hasMore: Boolean(next), source: 'sanity' } }
export async function getPublicExploreGuide(slug: string, preview = false) { const raw = await fetchExplore<any>(`*[_type == "exploreStudySet" && slug.current == $slug][0] ${projection}`, { slug }, preview); return raw ? normalizeGuide(raw) : fallbackGuide(slug) }
export async function getPublicExploreSlugs() { const rows = await fetchExplore<Array<{slug: string; publishedAt: string; image?: string}>>(`*[_type == "exploreStudySet" && defined(slug.current)] {"slug":slug.current,"publishedAt":_updatedAt,"image":coverImage.asset->url}`); return rows ?? [] }
