import type { Metadata } from 'next'
import Image from 'next/image'
import Link from 'next/link'
import { draftMode } from 'next/headers'
import { notFound } from 'next/navigation'
import { ArrowLeft, BookOpen, Clock, Target } from 'lucide-react'
import { GuideContent } from '@/components/explore/guide-content'
import { getPublicExploreGuide } from '@/lib/explore/service'
import { absoluteUrl } from '@/lib/site-config'

export const revalidate = 300
type Props = { params: Promise<{ slug: string }> }
export async function generateMetadata({ params }: Props): Promise<Metadata> { const { slug } = await params; const { isEnabled } = await draftMode(); const guide = await getPublicExploreGuide(slug, isEnabled); if (!guide) return {}; const title = guide.seo.title ?? guide.title; const description = guide.seo.description ?? guide.summary; const image = guide.seo.ogImage ?? guide.coverImage.url; return { title, description, robots: guide.seo.noIndex ? { index: false } : undefined, alternates: { canonical: guide.seo.canonicalUrl ?? `/explore/${guide.slug}` }, openGraph: { type: 'article', url: absoluteUrl(`/explore/${guide.slug}`), title, description, images: [{ url: image, alt: guide.coverImage.alt }] }, twitter: { card: 'summary_large_image', title, description, images: [image] } } }
export default async function GuidePage({ params }: Props) { const { slug } = await params; const { isEnabled } = await draftMode(); const guide = await getPublicExploreGuide(slug, isEnabled); if (!guide) notFound(); const jsonLd = { '@context': 'https://schema.org', '@type': 'LearningResource', name: guide.title, description: guide.summary, url: absoluteUrl(`/explore/${guide.slug}`), image: guide.coverImage.url, educationalLevel: guide.difficulty, timeRequired: `PT${guide.estimatedMinutes}M`, learningResourceType: guide.sections.map((x) => x.label), teaches: guide.learningObjectives } as const; return <main className="min-h-screen bg-[#f7f3ea] text-slate-950"><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd).replace(/</g, '\\u003c') }}/>
  <header className="border-b bg-white px-5 py-8 sm:px-8"><div className="mx-auto max-w-7xl"><Link href="/explore" className="inline-flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="h-4 w-4"/>Explore all guides</Link>{isEnabled ? <span className="ml-4 rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">Draft preview</span> : null}</div></header>
  <div className="mx-auto max-w-[1450px] px-4 py-8 sm:px-6 lg:grid lg:grid-cols-[180px_minmax(0,1fr)_300px] lg:gap-8">
    <nav aria-label="Study modes" className="sticky top-20 z-10 mb-7 flex gap-2 overflow-x-auto rounded-2xl border bg-white/95 p-2 lg:top-24 lg:mb-0 lg:h-fit lg:flex-col">{guide.sections.map((s) => <a key={s.type} href={`#mode-${s.type}`} className="whitespace-nowrap rounded-xl px-4 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100 hover:text-slate-950">{s.label}</a>)}</nav>
    <article><div className="relative aspect-[16/7] overflow-hidden rounded-[2rem] bg-slate-200"><Image src={guide.coverImage.url} alt={guide.coverImage.alt} fill priority sizes="(max-width:1024px) 100vw, 800px" className="object-cover"/></div><p className="mt-8 text-xs font-bold uppercase tracking-[.22em] text-orange-600">{guide.subject}</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.05em] sm:text-6xl">{guide.title}</h1><p className="mt-5 text-lg leading-8 text-slate-600">{guide.summary}</p><div className="my-10 space-y-16">{guide.sections.map((section, i) => <GuideContent key={`${section.type}-${i}`} section={section}/>)}</div></article>
    <aside className="h-fit rounded-[2rem] border bg-white p-6 lg:sticky lg:top-24"><h2 className="text-lg font-semibold">Guide information</h2><dl className="mt-5 space-y-4 text-sm"><div className="flex items-center gap-3"><Clock className="h-5 w-5 text-orange-600"/><div><dt className="text-slate-500">Estimated time</dt><dd className="font-semibold">{guide.estimatedMinutes} minutes</dd></div></div><div className="flex items-center gap-3"><BookOpen className="h-5 w-5 text-orange-600"/><div><dt className="text-slate-500">Difficulty</dt><dd className="font-semibold">{guide.difficulty}</dd></div></div></dl>{guide.learningObjectives.length ? <div className="mt-7 border-t pt-6"><h3 className="flex items-center gap-2 font-semibold"><Target className="h-5 w-5"/>You will learn</h3><ul className="mt-3 space-y-3 text-sm leading-6 text-slate-600">{guide.learningObjectives.map((x) => <li key={x}>• {x}</li>)}</ul></div> : null}<div className="mt-7 flex flex-wrap gap-2">{guide.tags.map((x) => <span key={x} className="rounded-full bg-slate-100 px-3 py-1 text-xs">{x}</span>)}</div></aside>
  </div></main> }
