import { PortableText } from '@portabletext/react'
import ReactMarkdown from 'react-markdown'
import type { ExploreSection } from '@/lib/explore/types'

const safeMedia = (url?: string) => url && /^https:\/\/(www\.)?(youtube\.com|youtu\.be|vimeo\.com|spotify\.com|soundcloud\.com)\//i.test(url) ? url : null
export function GuideContent({ section }: { section: ExploreSection }) {
  const items = section.items ?? []
  return <section id={`mode-${section.type}`} className="scroll-mt-28 space-y-6" aria-labelledby={`heading-${section.type}`}>
    <h2 id={`heading-${section.type}`} className="text-3xl font-semibold tracking-tight">{section.label}</h2>
    {Array.isArray(section.content) ? <div className="explore-prose"><PortableText value={section.content as any} /></div> : typeof section.content === 'string' ? <div className="explore-prose"><ReactMarkdown>{section.content}</ReactMarkdown></div> : null}
    {section.type === 'flashcards' && items.map((x, i) => <article key={i} className="rounded-3xl border bg-white p-6"><p className="text-xs font-bold uppercase tracking-widest text-orange-600">Prompt</p><h3 className="mt-2 text-lg font-semibold">{String(x.prompt ?? '')}</h3><div className="mt-5 border-t pt-5"><p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Answer</p><p className="mt-2 text-slate-700">{String(x.answer ?? '')}</p></div></article>)}
    {(section.type === 'mcq' || section.type === 'multiple_choice') && items.map((x, i) => <article key={i} className="rounded-3xl border bg-white p-6"><h3 className="font-semibold">{String(x.question ?? '')}</h3><ul className="mt-4 space-y-2">{(x.options as any[] ?? []).map((o, j) => { const correct = typeof o === 'object' ? o.correct : (x.optionIds as string[])?.[j] === x.correctOptionId; return <li key={j} className={`rounded-xl border p-3 ${correct ? 'border-emerald-400 bg-emerald-50 font-semibold text-emerald-900' : 'bg-slate-50'}`}>{typeof o === 'object' ? o.text : o}{correct ? ' ✓ Correct' : ''}</li> })}</ul>{x.explanation ? <p className="mt-4 text-sm text-slate-600">{String(x.explanation)}</p> : null}</article>)}
    {(section.type === 'fillBlank' || section.type === 'fill_in_blanks') && items.map((x, i) => <article key={i} className="rounded-3xl border bg-white p-6"><p>{String(x.prompt ?? x.sentence ?? '')}</p><p className="mt-4 rounded-xl bg-emerald-50 p-4 font-semibold text-emerald-900">Answer: {String(x.answer ?? '')}</p>{x.explanation ? <p className="mt-3 text-slate-600">{String(x.explanation)}</p> : null}</article>)}
    {(section.type === 'writtenTest' || section.type === 'written_test') && items.map((x, i) => <article key={i} className="rounded-3xl border bg-white p-6"><h3 className="font-semibold">{String(x.question ?? '')}</h3><p className="mt-4 text-sm font-bold text-emerald-800">Model answer</p><p className="mt-1 text-slate-700">{String(x.modelAnswer ?? x.idealResponse ?? '')}</p>{Array.isArray(x.markingPoints) ? <ul className="mt-3 list-disc pl-5">{x.markingPoints.map((p, j) => <li key={j}>{String(p)}</li>)}</ul> : null}</article>)}
    {items.length > 0 && !['flashcards','mcq','multiple_choice','fillBlank','fill_in_blanks','writtenTest','written_test'].includes(section.type) ? items.map((x, i) => <article key={i} className="rounded-3xl border bg-white p-6"><h3 className="font-semibold">{String(x.title ?? '')}</h3><p className="mt-2 text-slate-700">{String(x.text ?? x.summary ?? '')}</p></article>) : null}
    {safeMedia(section.url) ? <div className="space-y-4"><a href={section.url} target="_blank" rel="noreferrer noopener" className="inline-flex rounded-full bg-slate-950 px-5 py-3 font-semibold text-white">Open public media</a>{section.transcript?.length ? <div className="explore-prose"><h3>Transcript</h3><PortableText value={section.transcript as any} /></div> : null}</div> : null}
  </section>
}
