'use client'

import { useEffect, useMemo, useState } from 'react'
import { useRouter, useSearchParams } from 'next/navigation'
import { PortableText } from '@portabletext/react'
import ReactMarkdown from 'react-markdown'
import { ArrowLeft, BookOpen, ChevronLeft, ChevronRight, Edit3, FileText, GraduationCap, Headphones, Layers, ListChecks, LockKeyhole, MessageSquareText, PenSquare, Play, X } from 'lucide-react'
import type { ExploreGuide, ExploreSection } from '@/lib/explore/types'

const sectionMeta: Record<string, { label: string; icon: typeof BookOpen }> = {
  notes: { label: 'Notes', icon: FileText },
  flashcards: { label: 'Flashcards', icon: Layers },
  mcq: { label: 'Multiple Choice', icon: ListChecks },
  multiple_choice: { label: 'Multiple Choice', icon: ListChecks },
  fillBlank: { label: 'Fill in the Blanks', icon: Edit3 },
  fill_in_blanks: { label: 'Fill in the Blanks', icon: Edit3 },
  writtenTest: { label: 'Written Tests', icon: PenSquare },
  written_test: { label: 'Written Tests', icon: PenSquare },
  tutorLesson: { label: 'Tutor Lesson', icon: GraduationCap },
  tutor_lesson: { label: 'Tutor Lesson', icon: GraduationCap },
  media: { label: 'Podcast', icon: Headphones },
  podcast: { label: 'Podcast', icon: Headphones },
}

function updatedLabel(value: string) {
  const date = new Date(value)
  if (Number.isNaN(date.getTime())) return 'Recently'
  return date.toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' })
}

function sectionItems(section: ExploreSection) {
  if (section.type === 'notes') return []
  const items = section.items ?? []
  return items.length ? items : [{}]
}

function correctOption(item: Record<string, unknown>, option: unknown, index: number) {
  if (option && typeof option === 'object' && 'correct' in option) return Boolean((option as { correct?: boolean }).correct)
  const ids = Array.isArray(item.optionIds) ? item.optionIds : []
  if (typeof item.correctOptionId === 'string') return ids[index] === item.correctOptionId
  if (typeof item.answer === 'number') return item.answer === index
  return typeof item.answer === 'string' && String(option).trim().toLowerCase() === item.answer.trim().toLowerCase()
}

function youtubeEmbedUrl(value?: string) {
  if (!value) return null
  try { const url = new URL(value); const host = url.hostname.replace(/^www\./, ''); const id = host === 'youtu.be' ? url.pathname.split('/').filter(Boolean)[0] : url.searchParams.get('v') ?? (url.pathname.startsWith('/embed/') ? url.pathname.split('/')[2] : null); return id && /^[\w-]{6,}$/.test(id) ? `https://www.youtube.com/embed/${id}` : null } catch { return null }
}

function Notes({ section }: { section: ExploreSection }) {
  return <div className="min-h-full bg-white px-5 pb-24 pt-2 sm:px-8">
    <div className="mx-auto max-w-[820px] [&_blockquote]:border-l-4 [&_blockquote]:border-primary [&_blockquote]:pl-4 [&_h1]:mb-6 [&_h1]:text-4xl [&_h1]:font-bold [&_h2]:mb-3 [&_h2]:mt-8 [&_h2]:text-2xl [&_h2]:font-bold [&_li]:ml-5 [&_li]:list-disc [&_p]:my-4 [&_p]:leading-8 [&_p]:text-foreground/80">
      {Array.isArray(section.content) ? <PortableText value={section.content as any} /> : <ReactMarkdown>{typeof section.content === 'string' ? section.content : 'No notes available.'}</ReactMarkdown>}
    </div>
  </div>
}

function ReadOnlyItem({ section, item }: { section: ExploreSection; item: Record<string, unknown> }) {
  const type = section.type
  if (type === 'flashcards') return <div className="space-y-4"><p className="text-sm uppercase tracking-wide text-muted-foreground">Flashcard</p><div className="grid min-h-[320px] overflow-hidden rounded-3xl border-2 border-primary/40 bg-gradient-to-br from-primary/5 to-primary/10 shadow-sm sm:grid-cols-2"><div className="flex flex-col items-center justify-center border-b border-primary/20 p-7 text-center sm:border-b-0 sm:border-r sm:p-10"><p className="mb-4 text-xs uppercase tracking-widest text-primary/60">Prompt</p><p className="text-xl font-semibold leading-snug sm:text-2xl">{String(item.prompt ?? 'Prompt unavailable')}</p></div><div className="flex flex-col items-center justify-center p-7 text-center sm:p-10"><p className="mb-4 text-xs uppercase tracking-widest text-primary/60">Answer</p><p className="text-xl font-semibold leading-snug sm:text-2xl">{String(item.answer ?? 'Answer unavailable')}</p></div></div><p className="text-center text-xs text-muted-foreground">Public guide · prompt and answer are shown together</p></div>

  if (type === 'mcq' || type === 'multiple_choice') { const options = Array.isArray(item.options) ? item.options : []; return <div className="space-y-6"><div><p className="mb-2 text-sm uppercase tracking-wide text-muted-foreground">Multiple Choice</p><h2 className="text-xl font-semibold sm:text-2xl">{String(item.question ?? 'Practice question')}</h2></div><div className="grid grid-cols-1 gap-3 sm:grid-cols-2">{options.map((option, index) => { const correct = correctOption(item, option, index); const text = option && typeof option === 'object' ? (option as { text?: unknown }).text : option; return <div key={index} className={`flex items-start gap-3 rounded-2xl border p-4 ${correct ? 'border-green-500 bg-green-50' : 'border-border bg-card'}`}><span className={`flex h-8 w-8 shrink-0 items-center justify-center rounded-full text-sm font-semibold ${correct ? 'bg-green-600 text-white' : 'bg-secondary'}`}>{index + 1}</span><div><p className="text-sm leading-relaxed">{String(text ?? '')}</p>{correct ? <p className="mt-1 text-xs font-semibold text-green-700">Correct answer</p> : null}</div></div> })}</div>{item.explanation ? <div className="rounded-2xl border border-green-300 bg-green-50 p-4 text-sm text-green-800"><p className="mb-1 font-semibold text-foreground">Explanation</p><p>{String(item.explanation)}</p></div> : null}</div> }

  if (type === 'fillBlank' || type === 'fill_in_blanks') return <div className="space-y-4"><p className="text-sm uppercase tracking-wide text-muted-foreground">Fill in the Blank</p><div className="space-y-4 rounded-2xl border bg-card p-4 sm:p-6"><p className="text-lg">{String(item.prompt ?? item.sentence ?? 'Complete the sentence.')}</p><div className="rounded-xl border border-green-300 bg-green-50 p-4 text-sm text-green-800"><p className="mb-1 font-semibold text-foreground">Correct answer</p><p>{String(item.answer ?? 'N/A')}</p>{item.explanation ? <p className="mt-2">{String(item.explanation)}</p> : null}</div></div></div>

  if (type === 'writtenTest' || type === 'written_test') { const points = Array.isArray(item.markingPoints) ? item.markingPoints : Array.isArray(item.rubric) ? item.rubric : []; return <div className="space-y-4"><p className="text-sm uppercase tracking-wide text-muted-foreground">Written Test</p><div className="space-y-4 rounded-2xl border bg-card p-4 sm:p-6"><div><p className="mb-1 text-xs uppercase text-muted-foreground">Prompt</p><p className="text-lg font-semibold">{String(item.question ?? item.prompt ?? 'Written question')}</p></div><div className="rounded-xl border bg-secondary/40 p-4"><p className="mb-1 text-xs uppercase text-muted-foreground">Model Answer</p><p className="text-sm leading-relaxed">{String(item.modelAnswer ?? item.idealResponse ?? '')}</p></div>{points.length ? <div><p className="mb-2 text-xs uppercase text-muted-foreground">Marking points</p><ul className="space-y-2 text-sm">{points.map((point, index) => <li key={index} className="flex gap-2"><span className="text-primary">•</span>{String(point)}</li>)}</ul></div> : null}</div></div> }

  if (type === 'tutorLesson' || type === 'tutor_lesson') return <div className="space-y-6"><div className="space-y-3 rounded-2xl border bg-card p-5"><p className="text-xs uppercase text-muted-foreground">Tutor Prompt</p><p className="text-lg font-semibold">{String(item.prompt ?? item.title ?? 'Guided lesson')}</p></div><div className="space-y-3 rounded-2xl border bg-card p-5"><p className="text-xs uppercase text-muted-foreground">Suggested Response</p><p className="whitespace-pre-wrap text-sm leading-relaxed">{String(item.response ?? item.text ?? '')}</p></div>{item.followUp ? <div className="rounded-2xl border border-dashed bg-card p-4"><p className="mb-1 text-xs uppercase text-muted-foreground">Follow-up</p><p className="text-sm">{String(item.followUp)}</p></div> : null}</div>

  const safeUrl = section.url && /^https:\/\//.test(section.url) ? section.url : null
  return <div className="space-y-4"><p className="text-sm uppercase tracking-wide text-muted-foreground">Podcast</p><div className="space-y-4 rounded-2xl border bg-card p-5"><div className="flex items-center justify-between gap-3"><div><p className="text-xs uppercase text-muted-foreground">Episode</p><h2 className="mt-1 text-lg font-semibold">{String(item.title ?? 'Audio lesson')}</h2></div><span className="rounded-full bg-primary/10 px-3 py-1 text-xs font-semibold text-primary">Conversational</span></div>{safeUrl ? <a href={safeUrl} target="_blank" rel="noreferrer noopener" className="inline-flex rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Open media</a> : null}{Array.isArray(item.talkingPoints) ? <ul className="space-y-2 text-sm">{item.talkingPoints.map((point, index) => <li key={index} className="flex gap-2"><span className="mt-2 h-1.5 w-1.5 shrink-0 rounded-full bg-primary"/>{String(point)}</li>)}</ul> : null}</div>{section.transcript?.length ? <div className="rounded-2xl border bg-card p-5"><p className="mb-4 text-xs uppercase text-muted-foreground">Transcript</p><PortableText value={section.transcript as any}/></div> : null}</div>
}

export function PublicStudySetReader({ guide, preview }: { guide: ExploreGuide; preview: boolean }) {
  const router = useRouter(); const searchParams = useSearchParams()
  const requested = searchParams.get('mode')
  const initial = guide.sections.find((section) => section.type === requested)?.type ?? guide.sections[0]?.type ?? null
  const [activeType, setActiveType] = useState<string | null>(initial); const [index, setIndex] = useState(0)
  const [sideTab, setSideTab] = useState<'chat' | 'content' | 'notes'>('content'); const [loginWarning, setLoginWarning] = useState(false)
  useEffect(() => { const valid = guide.sections.find((section) => section.type === requested)?.type; if (valid) { setActiveType(valid); setIndex(0) } }, [guide.sections, requested])
  const active = useMemo(() => guide.sections.find((section) => section.type === activeType) ?? guide.sections[0], [activeType, guide.sections])
  const items = active ? sectionItems(active) : []; const item = items[index] ?? items[0]
  const open = (type: string) => { setActiveType(type); setIndex(0); router.replace(`/explore/${guide.slug}?mode=${encodeURIComponent(type)}`, { scroll: false }) }
  const video = youtubeEmbedUrl(guide.publicContent?.videoUrl) ?? youtubeEmbedUrl(guide.sections.find((section) => section.url)?.url)
  return <div className="flex h-[calc(100dvh-76px)] min-h-[620px] bg-[#fffaf5]">
    <div className="flex min-w-0 flex-1 flex-col">
      <header className="z-30 min-h-[70px] shrink-0 border-b border-border bg-white/90 px-3 py-3 backdrop-blur-sm sm:px-5 lg:px-8"><div className="flex items-center gap-2 sm:gap-4"><button onClick={() => router.push('/explore')} aria-label="Back to Explore" className="inline-flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-border bg-background transition-colors hover:bg-secondary"><ArrowLeft className="h-5 w-5"/></button><div className="flex min-w-0 flex-1 items-center gap-2 lg:gap-8"><h1 className="min-w-0 flex-1 truncate text-base font-bold sm:text-xl">{guide.title}</h1></div><div className="hidden shrink-0 text-right text-sm text-muted-foreground xl:block"><p className="text-xs uppercase tracking-[.2em]">Last updated</p><p className="mt-1 text-base text-foreground">{updatedLabel(guide.publishedAt)}</p></div>{preview ? <span className="rounded-full bg-amber-100 px-3 py-1 text-xs font-bold text-amber-900">Draft preview</span> : null}</div>
        <nav aria-label="Study modes" className="mt-2 w-full overflow-hidden lg:hidden"><div className="flex max-w-full gap-2 overflow-x-auto [scrollbar-width:none]">{guide.sections.map((section) => { const meta = sectionMeta[section.type] ?? { label: section.label, icon: BookOpen }; const Icon = meta.icon; const selected = active?.type === section.type; return <button key={section.type} onClick={() => open(section.type)} className={`inline-flex min-h-10 shrink-0 items-center gap-1.5 rounded-xl border px-3 py-2 text-xs font-semibold ${selected ? 'border-primary bg-primary text-primary-foreground' : 'border-border bg-white text-muted-foreground'}`}><Icon className="h-4 w-4"/>{meta.label}</button> })}</div></nav>
      </header>
      <div className="flex min-h-0 flex-1">
        <aside className="hidden w-[250px] shrink-0 border-r border-border bg-white p-4 lg:block"><nav aria-label="Study modes" className="sticky top-4 space-y-2">{guide.sections.map((section) => { const meta = sectionMeta[section.type] ?? { label: section.label, icon: BookOpen }; const Icon = meta.icon; const selected = active?.type === section.type; return <button key={section.type} onClick={() => open(section.type)} aria-current={selected ? 'page' : undefined} className={`flex w-full items-center gap-3 rounded-xl border px-4 py-3 text-left text-sm font-semibold transition-colors ${selected ? 'border-primary bg-primary text-primary-foreground shadow-sm' : 'border-transparent bg-white text-muted-foreground hover:border-primary/30 hover:bg-secondary/40 hover:text-primary'}`}><Icon className="h-5 w-5 shrink-0"/><span>{meta.label}</span></button> })}</nav></aside>
        <main className="min-h-0 min-w-0 flex-1 overflow-y-auto pt-4"><section className="mx-auto min-w-0 max-w-[1400px] flex-1">{active?.type === 'notes' ? <Notes section={active}/> : active && item ? <div className="px-2 pb-6 sm:px-4"><div className="mx-auto flex max-w-[700px] items-center gap-3"><span className="mb-3 rounded-full border bg-white px-3 py-1.5 text-xs font-semibold text-muted-foreground">Item {index + 1} of {items.length}</span><span className="mb-3 rounded-full border border-primary/20 bg-primary/5 px-3 py-1.5 text-xs font-semibold text-primary">Read only</span></div><div className="mx-auto h-full max-w-[700px] rounded-[20px] border bg-card p-4 shadow-sm sm:rounded-[28px] sm:p-6"><ReadOnlyItem section={active} item={item}/></div>{items.length > 1 ? <div className="mx-auto mt-4 flex max-w-[700px] items-center gap-3"><button onClick={() => setIndex((value) => Math.max(0, value - 1))} disabled={index === 0} className="flex flex-1 items-center justify-center gap-2 rounded-2xl border bg-white px-4 py-3 text-sm font-semibold hover:bg-secondary/50 disabled:opacity-50"><ChevronLeft className="h-4 w-4"/>Previous</button><button onClick={() => setIndex((value) => Math.min(items.length - 1, value + 1))} disabled={index === items.length - 1} className="flex flex-1 items-center justify-center gap-2 rounded-2xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-50">Next<ChevronRight className="h-4 w-4"/></button></div> : null}</div> : <div className="p-10 text-center text-muted-foreground">No public content is available for this mode.</div>}</section></main>
        <aside className="hidden w-[360px] shrink-0 border-l border-border bg-white xl:flex xl:min-h-0 xl:flex-col"><div className="m-4 grid grid-cols-3 rounded-xl bg-secondary/60 p-1">{(['chat','content','notes'] as const).map((tab) => <button key={tab} onClick={() => { setSideTab(tab); if (tab === 'chat') setLoginWarning(true) }} className={`flex items-center justify-center gap-1.5 rounded-lg px-2 py-2.5 text-xs font-semibold capitalize ${sideTab === tab ? 'bg-white text-foreground shadow-sm' : 'text-muted-foreground'}`}>{tab === 'chat' ? <MessageSquareText className="h-3.5 w-3.5"/> : tab === 'content' ? <FileText className="h-3.5 w-3.5"/> : <BookOpen className="h-3.5 w-3.5"/>}{tab}</button>)}</div><div className="min-h-0 flex-1 overflow-y-auto px-4 pb-5">{sideTab === 'content' ? <div className="space-y-5">{video ? <div className="aspect-video overflow-hidden rounded-xl border bg-black"><iframe src={video} title={guide.publicContent?.title ?? `${guide.title} video`} className="h-full w-full border-0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowFullScreen/></div> : <div className="flex aspect-video flex-col items-center justify-center rounded-xl border border-dashed bg-secondary/20 text-center text-sm text-muted-foreground"><Play className="mb-2 h-7 w-7"/><p>No public video added yet.</p><p className="mt-1 text-xs">Add one from Sanity Studio.</p></div>}<div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-muted-foreground">Transcript</p>{guide.publicContent?.transcript?.length ? <div className="space-y-3 rounded-xl border p-4 text-sm leading-6"><PortableText value={guide.publicContent.transcript as any}/></div> : <p className="rounded-xl border border-dashed p-4 text-sm text-muted-foreground">No transcript has been published.</p>}</div></div> : sideTab === 'notes' ? <div><p className="mb-3 text-xs font-bold uppercase tracking-widest text-muted-foreground">Guide Notes</p>{guide.sidebarNotes?.length ? <div className="space-y-3 text-sm leading-6"><PortableText value={guide.sidebarNotes as any}/></div> : active?.type === 'notes' ? <div className="text-sm leading-6">Use the main reader to review the full notes.</div> : <p className="text-sm text-muted-foreground">No sidebar notes have been published.</p>}</div> : <button onClick={() => setLoginWarning(true)} className="flex h-full min-h-64 w-full flex-col items-center justify-center rounded-xl border border-dashed bg-secondary/20 p-6 text-center"><LockKeyhole className="h-8 w-8 text-primary"/><p className="mt-4 font-semibold">Chat requires an account</p><p className="mt-2 text-sm text-muted-foreground">Sign in to ask questions about this study guide.</p></button>}</div></aside>
      </div>
      <div className="border-t bg-white p-2 xl:hidden"><div className="mx-auto grid max-w-sm grid-cols-3 rounded-xl bg-secondary/60 p-1"><button onClick={() => setLoginWarning(true)} className="flex items-center justify-center gap-1.5 rounded-lg px-2 py-2 text-xs font-semibold text-muted-foreground"><MessageSquareText className="h-3.5 w-3.5"/>Chat</button><button onClick={() => setSideTab('content')} className="rounded-lg bg-white px-2 py-2 text-xs font-semibold shadow-sm">Content</button><button onClick={() => setSideTab('notes')} className="px-2 py-2 text-xs font-semibold text-muted-foreground">Notes</button></div></div>
      {loginWarning ? <div className="fixed inset-0 z-[100] flex items-center justify-center bg-slate-950/50 p-4 backdrop-blur-sm" role="dialog" aria-modal="true" aria-labelledby="login-warning-title" onMouseDown={(event) => { if (event.target === event.currentTarget) setLoginWarning(false) }}><div className="relative w-full max-w-md rounded-3xl bg-white p-7 shadow-2xl"><button onClick={() => setLoginWarning(false)} aria-label="Close" className="absolute right-4 top-4 rounded-full p-2 text-muted-foreground hover:bg-secondary"><X className="h-5 w-5"/></button><div className="flex h-12 w-12 items-center justify-center rounded-2xl bg-primary/10 text-primary"><LockKeyhole className="h-6 w-6"/></div><h2 id="login-warning-title" className="mt-5 text-2xl font-bold">Sign in to use chat</h2><p className="mt-3 leading-7 text-muted-foreground">This Explore guide is public and read-only. Chat is available only to authenticated Neurova users.</p><div className="mt-6 flex gap-3"><button onClick={() => setLoginWarning(false)} className="flex-1 rounded-xl border px-4 py-3 text-sm font-semibold">Continue reading</button><button onClick={() => router.push(`/login?next=${encodeURIComponent(`/explore/${guide.slug}`)}`)} className="flex-1 rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground">Sign in</button></div></div></div> : null}
    </div>
  </div>
}
